import fs from "fs";
import path from "path";
import pg from "pg";

const { Client } = pg;

const client = new Client({
    connectionString: process.env.DATABASE_URL,
});

const dbPath = path.join(process.cwd(), "data", "db.json");

function calcularDataMensagem(hora) {
    if (!hora) return new Date();

    const partes = hora.split(":");

    if (partes.length !== 2) {
        return new Date();
    }

    const agora = new Date();

    agora.setHours(
        Number(partes[0]) || 0,
        Number(partes[1]) || 0,
        0,
        0
    );

    return agora;
}

async function criarTabelas() {
    await client.query(`
    CREATE TABLE IF NOT EXISTS portadores (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL UNIQUE,
      nome VARCHAR(120) NOT NULL,
      idade VARCHAR(30),
      condicao VARCHAR(120),
      humor VARCHAR(120),
      humor_emoji VARCHAR(20),
      local VARCHAR(255),
      distancia_metros INTEGER DEFAULT 0,
      pin_x NUMERIC(8, 2) DEFAULT 50,
      pin_y NUMERIC(8, 2) DEFAULT 50,
      geofence_max INTEGER DEFAULT 150,
      bateria INTEGER DEFAULT 100,
      criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_portador_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
    );
  `);

    await client.query(`
    CREATE TABLE IF NOT EXISTS rotinas (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      portador_id BIGINT NOT NULL,
      hora VARCHAR(10) NOT NULL,
      titulo VARCHAR(255) NOT NULL,
      concluida BOOLEAN DEFAULT FALSE,
      criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_rotina_portador
        FOREIGN KEY (portador_id)
        REFERENCES portadores(id)
        ON DELETE CASCADE,

      CONSTRAINT uq_rotina
        UNIQUE (portador_id, hora, titulo)
    );
  `);

    await client.query(`
    CREATE TABLE IF NOT EXISTS metas (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      portador_id BIGINT NOT NULL,
      titulo VARCHAR(255) NOT NULL,
      progresso INTEGER DEFAULT 0,
      criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_meta_portador
        FOREIGN KEY (portador_id)
        REFERENCES portadores(id)
        ON DELETE CASCADE,

      CONSTRAINT uq_meta
        UNIQUE (portador_id, titulo)
    );
  `);

    await client.query(`
    CREATE TABLE IF NOT EXISTS mensagens (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      portador_id BIGINT NOT NULL,
      texto TEXT NOT NULL,
      hora VARCHAR(10),
      criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_mensagem_portador
        FOREIGN KEY (portador_id)
        REFERENCES portadores(id)
        ON DELETE CASCADE,

      CONSTRAINT uq_mensagem
        UNIQUE (portador_id, texto, hora)
    );
  `);

    await client.query(`
    CREATE TABLE IF NOT EXISTS localizacoes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      portador_id BIGINT NOT NULL,
      latitude NUMERIC(10, 7),
      longitude NUMERIC(10, 7),
      bateria INTEGER,
      registrada_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_localizacao_portador
        FOREIGN KEY (portador_id)
        REFERENCES portadores(id)
        ON DELETE CASCADE
    );
  `);

    await client.query(`
    CREATE TABLE IF NOT EXISTS emergencias (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      portador_id BIGINT NOT NULL,
      acionada_por BIGINT,
      latitude NUMERIC(10, 7),
      longitude NUMERIC(10, 7),
      status VARCHAR(30) DEFAULT 'aberta',
      criada_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_emergencia_portador
        FOREIGN KEY (portador_id)
        REFERENCES portadores(id)
        ON DELETE CASCADE,

      CONSTRAINT fk_emergencia_usuario
        FOREIGN KEY (acionada_por)
        REFERENCES users(id)
        ON DELETE SET NULL
    );
  `);

    await client.query(`
    CREATE TABLE IF NOT EXISTS logs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      time VARCHAR(20),
      type VARCHAR(50),
      user_name VARCHAR(120),
      user_id BIGINT,
      action TEXT,
      level VARCHAR(30),
      criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_log_usuario
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
    );
  `);

    await client.query(`
    CREATE TABLE IF NOT EXISTS disponiveis (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome VARCHAR(120) NOT NULL,
      idade VARCHAR(30),
      condicao VARCHAR(120),
      local VARCHAR(255),
      geofence_max INTEGER DEFAULT 150,
      criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
  `);


    await client.query(`
    CREATE TABLE IF NOT EXISTS acompanhante_portador (
      acompanhante_id BIGINT NOT NULL,
      portador_id BIGINT NOT NULL UNIQUE,
      criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT pk_acompanhante_portador
        PRIMARY KEY (acompanhante_id, portador_id),
      CONSTRAINT fk_vinculo_acompanhante
        FOREIGN KEY (acompanhante_id)
        REFERENCES users(id) ON DELETE CASCADE,
      CONSTRAINT fk_vinculo_portador
        FOREIGN KEY (portador_id)
        REFERENCES portadores(id) ON DELETE CASCADE
    );
  `);

    await client.query(`
      CREATE INDEX IF NOT EXISTS idx_vinculo_acompanhante
      ON acompanhante_portador(acompanhante_id);
    `);
}

async function migrarPortadores(db) {
    let quantidade = 0;

    for (const portador of db.portadores || []) {
        const userResult = await client.query(
            `
      SELECT id
      FROM users
      WHERE LOWER(name) = LOWER($1)
      LIMIT 1
      `,
            [portador.nome]
        );

        if (userResult.rows.length === 0) {
            console.log(
                `⚠ Portador ignorado: usuário não encontrado para "${portador.nome}"`
            );
            continue;
        }

        const userId = userResult.rows[0].id;

        const result = await client.query(
            `
      INSERT INTO portadores (
        user_id,
        nome,
        idade,
        condicao,
        humor,
        humor_emoji,
        local,
        distancia_metros,
        pin_x,
        pin_y,
        geofence_max,
        bateria
      )
      VALUES (
        $1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11, $12
      )
      ON CONFLICT (user_id)
      DO UPDATE SET
        nome = EXCLUDED.nome,
        idade = EXCLUDED.idade,
        condicao = EXCLUDED.condicao,
        humor = EXCLUDED.humor,
        humor_emoji = EXCLUDED.humor_emoji,
        local = EXCLUDED.local,
        distancia_metros = EXCLUDED.distancia_metros,
        pin_x = EXCLUDED.pin_x,
        pin_y = EXCLUDED.pin_y,
        geofence_max = EXCLUDED.geofence_max,
        bateria = EXCLUDED.bateria
      RETURNING id
      `,
            [
                userId,
                portador.nome || "",
                portador.idade || null,
                portador.condicao || null,
                portador.humor || null,
                portador.humorEmoji || null,
                portador.local || null,
                Number(portador.distanciaMetros) || 0,
                Number(portador.pinX) || 50,
                Number(portador.pinY) || 50,
                Number(portador.geofenceMax) || 150,
                Number(portador.bateria) || 100,
            ]
        );

        const portadorId = result.rows[0].id;

        await migrarRotinas(portadorId, portador.rotinas || []);
        await migrarMetas(portadorId, portador.metas || []);
        await migrarMensagens(portadorId, portador.mensagens || []);

        quantidade++;

        console.log(
            `✓ Portador migrado: ${portador.nome}`
        );
    }

    return quantidade;
}

async function migrarRotinas(portadorId, rotinas) {
    for (const rotina of rotinas) {
        await client.query(
            `
      INSERT INTO rotinas (
        portador_id,
        hora,
        titulo,
        concluida
      )
      VALUES ($1, $2, $3, $4)
      ON CONFLICT (portador_id, hora, titulo)
      DO UPDATE SET
        concluida = EXCLUDED.concluida
      `,
            [
                portadorId,
                rotina.hora || "00:00",
                rotina.titulo || "Sem título",
                Boolean(rotina.concluida),
            ]
        );
    }
}

async function migrarMetas(portadorId, metas) {
    for (const meta of metas) {
        await client.query(
            `
      INSERT INTO metas (
        portador_id,
        titulo,
        progresso
      )
      VALUES ($1, $2, $3)
      ON CONFLICT (portador_id, titulo)
      DO UPDATE SET
        progresso = EXCLUDED.progresso
      `,
            [
                portadorId,
                meta.titulo || "Sem título",
                Number(meta.progresso) || 0,
            ]
        );
    }
}

async function migrarMensagens(portadorId, mensagens) {
    for (const mensagem of mensagens) {
        await client.query(
            `
      INSERT INTO mensagens (
        portador_id,
        texto,
        hora,
        criado_em
      )
      VALUES ($1, $2, $3, $4)
      ON CONFLICT (portador_id, texto, hora)
      DO NOTHING
      `,
            [
                portadorId,
                mensagem.texto || "",
                mensagem.hora || null,
                calcularDataMensagem(mensagem.hora),
            ]
        );
    }
}

async function migrarLogs(db) {
    let quantidade = 0;

    const existing = await client.query(
        "SELECT COUNT(*)::int AS total FROM logs"
    );

    // Evita duplicar os mesmos logs toda vez que o script for executado.
    if (existing.rows[0].total > 0) {
        console.log(
            `- Logs já existem no banco. Nenhum log antigo foi duplicado.`
        );
        return 0;
    }

    for (const log of db.logs || []) {
        const userResult = await client.query(
            `
      SELECT id
      FROM users
      WHERE LOWER(name) = LOWER($1)
      LIMIT 1
      `,
            [log.user || ""]
        );

        const userId =
            userResult.rows.length > 0
                ? userResult.rows[0].id
                : null;

        await client.query(
            `
      INSERT INTO logs (
        time,
        type,
        user_name,
        user_id,
        action,
        level
      )
      VALUES ($1, $2, $3, $4, $5, $6)
      `,
            [
                log.time || null,
                log.type || null,
                log.user || null,
                userId,
                log.action || null,
                log.level || null,
            ]
        );

        quantidade++;
    }

    return quantidade;
}

async function migrarDisponiveis(db) {
    let quantidade = 0;

    for (const item of db.disponiveis || []) {
        await client.query(
            `
      INSERT INTO disponiveis (
        nome,
        idade,
        condicao,
        local,
        geofence_max
      )
      VALUES ($1, $2, $3, $4, $5)
      `,
            [
                item.nome || "",
                item.idade || null,
                item.condicao || null,
                item.local || null,
                Number(item.geofenceMax) || 150,
            ]
        );

        quantidade++;
    }

    return quantidade;
}

async function main() {
    try {
        console.log("======================================");
        console.log(" MIGRAÇÃO DO HEART TECH");
        console.log("======================================\n");

        if (!fs.existsSync(dbPath)) {
            throw new Error(
                `Arquivo não encontrado: ${dbPath}`
            );
        }

        const arquivo = fs.readFileSync(
            dbPath,
            "utf-8"
        );

        const db = JSON.parse(arquivo);

        await client.connect();

        console.log("✓ Conectado ao PostgreSQL.\n");

        await client.query("BEGIN");

        console.log("Criando tabelas...");

        await criarTabelas();

        console.log("✓ Tabelas criadas/verificadas.\n");

        console.log("Migrando portadores...");

        const portadores = await migrarPortadores(db);

        console.log(
            `✓ ${portadores} portador(es) processado(s).\n`
        );

        console.log("Migrando logs...");

        const logs = await migrarLogs(db);

        console.log(
            `✓ ${logs} log(s) processado(s).\n`
        );

        console.log("Migrando disponíveis...");

        const disponiveis = await migrarDisponiveis(db);

        console.log(
            `✓ ${disponiveis} disponível(is) processado(s).\n`
        );

        await client.query("COMMIT");

        console.log("======================================");
        console.log(" MIGRAÇÃO CONCLUÍDA COM SUCESSO");
        console.log("======================================");

        console.log("\nTabelas do Heart Tech:");
        console.log("✓ users");
        console.log("✓ portadores");
        console.log("✓ rotinas");
        console.log("✓ metas");
        console.log("✓ mensagens");
        console.log("✓ localizacoes");
        console.log("✓ emergencias");
        console.log("✓ logs");
        console.log("✓ disponiveis");
    } catch (error) {
        try {
            await client.query("ROLLBACK");
        } catch { }

        console.error("\n❌ ERRO NA MIGRAÇÃO:");
        console.error(error);
    } finally {
        await client.end();
    }
}

main();